name: Laravel Installation Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run tests weekly on Sunday at 0:00 UTC
    - cron: '0 0 * * 0'

jobs:
  laravel-installation-test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.1', '8.2', '8.3', '8.4']
        laravel-version: ['9.*', '10.*', '11.*', '12.*']
        exclude:
          # Laravel 9 requires PHP 8.0+, we start from 8.1
          # Laravel 10 requires PHP 8.1+
          # Laravel 11 requires PHP 8.2+  
          # Laravel 12 requires PHP 8.3+
          - php-version: '8.1'
            laravel-version: '11.*'
          - php-version: '8.1'
            laravel-version: '12.*'
          - php-version: '8.2'
            laravel-version: '12.*'
    
    name: PHP ${{ matrix.php-version }} - Laravel ${{ matrix.laravel-version }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none
      
      - name: Create Laravel application
        run: |
          composer create-project laravel/laravel:${{ matrix.laravel-version }} laravel-test-app --prefer-dist --no-progress --no-interaction
          cd laravel-test-app
          php artisan --version
      
      - name: Install package via Composer
        working-directory: laravel-test-app
        run: |
          # Install the package from local source (simulating Packagist installation)
          composer config repositories.local-package path ../
          composer require egyjs/progressive-json-php:@dev --no-interaction
      
      - name: Verify package installation
        working-directory: laravel-test-app
        run: |
          # Check if the package is listed in composer.json
          composer show egyjs/progressive-json-php
          
          # Verify autoloading works
          php -r "
            require_once 'vendor/autoload.php';
            if (class_exists('Egyjs\ProgressiveJson\ProgressiveJsonStreamer')) {
              echo 'Package autoloaded successfully' . PHP_EOL;
            } else {
              echo 'Package autoloading failed' . PHP_EOL;
              exit(1);
            }
          "
      
      - name: Copy and run PHPUnit tests
        working-directory: laravel-test-app
        run: |
          # Copy the package tests to Laravel test directory
          cp -r ../tests/* tests/
          cp ../phpunit.xml ./phpunit-package.xml
          
          # Run the package tests within Laravel context
          ./vendor/bin/phpunit --configuration=phpunit-package.xml --testdox
      

  installation-summary:
    runs-on: ubuntu-latest
    needs: laravel-installation-test
    if: always()
    
    steps:
      - name: Installation Test Summary
        run: |
          echo "## Laravel Installation Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Installation tests completed for Laravel versions 9.x through 12.x" >> $GITHUB_STEP_SUMMARY
          echo "across PHP versions 8.1 through 8.4" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Package installation verification" >> $GITHUB_STEP_SUMMARY
          echo "✅ PHPUnit test execution in Laravel context" >> $GITHUB_STEP_SUMMARY
          echo "✅ Laravel integration testing" >> $GITHUB_STEP_SUMMARY
